export const DECREASE = "DECREASE"
export const INCREASE = "INCREASE"
export const RESET = "RESET"
export const CHANGE_NAME = "CHANGE_NAME"
export const REMOVE = "REMOVE"
export const GET_TOTAL = "GET_TOTAL"
export const GET_AMOUNT = "GET_AMOUNT"
